name: Merge bam files for replicates
description: Merge bam files for replicates and generate bigwig files. 
keywords:
    - mergeBam
tools:
    - samtools:
        description: |
            SAMtools is a set of utilities for interacting with and post-processing
            short DNA sequence read alignments in the SAM, BAM and CRAM formats, written by Heng Li.
            These files are generated as output by short read aligners like BWA.
        homepage: http://www.htslib.org/
        documentation: hhttp://www.htslib.org/doc/samtools.html
        doi: 10.1093/bioinformatics/btp352
    - deepTools:
        description: |
            deepTools is a suite of python tools particularly developed for the 
            efficient analysis of high-throughput sequencing data, such as 
            ChIP-seq, RNA-seq or MNase-seq.
        homepage: https://deeptools.readthedocs.io/
        documentation: https://deeptools.readthedocs.io/en/develop/
        doi: 10.1093/nar/gkw257
input:
    -
        - input:
            type: file
            description: Treatment BAM file and its input BAM file (optional)
            pattern: "*.{bam}"
output:
    -
        - bw:
            type: file
            description: bigWig files
            pattern: "*.{bw}"
        - bam:
            type: file
            description: Merged BAM file
            pattern: "*.{bam, bai}"
authors:
    - "@jianhong"